config/routes.rb
Ckm::Application.routes.draw do
 

  get 'upload' => 'uploads#index'
  post 'upload' => 'uploads#upload'

  get "/bbs/" => redirect("/bbs/forum.php")
  # get '/bbs/:name', to: redirect('/bbs/%{name}')

  #get '/bbs/(:name)', to: redirect('http://www.chekuaimei.com/bbs/%{name}'), constraints: lambda { |request| ['www.ckm888.com', 'ckm888.com', '121.199.5.92'].include?(request.host) }

  mount UeditorRails::Engine => '/ueditor'

  get "service/category/:id/(page/:page)" => "service#category", :as => :category
  resources :service
  resources :downloads
  get "contact" => "contact#index"
  resources :shenqing
  resources :news do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :jiameng
  resources :zs

  get 'about/' => redirect("/about/1")
  get 'about/(:id)' => 'abouts#show'
  # get 'about/(:id)' => 'abouts#show', :constraints => {:id => /[1-4]/}

  resources :partners do
    get 'code/(:code)' =>  "partners#code", :on => :collection
  end

  namespace :admin do
    get 'showpartners/(:id)' => 'agents#get_partners'
    get 'regions/(:id)' => 'partners#get_regions'


    resources :qqs
    resources :friendlinks
    resources :shenqings
    resources :jiamengs
    resources :downloads
    resources :teams
    resources :shops
    resources :partners
    resources :users
    resources :sessions
    get 'sessions/logout' => 'sessions#destroy'

    get "" => 'home#index'
    # resources :admin

    # Directs /admin/products/* to Admin::ProductsController
    # (app/controllers/admin/products_controller.rb)
    resources :products
    resources :categories
    resources :indexsets
    resources :articles
    resources :zhaoshangs
    resources :abouts
    resources :agents
  end

  root :to => 'home#index'

end

app/models/friendlink.rb
# encoding: utf-8

class Friendlink < ActiveRecord::Base
  attr_accessible :web_name, :url, :state
  validates :web_name, :presence => { message: "名称不能为空"}
  validates :url,
            :presence => { :message => "连接地址不能为空" },
            :format => { :with => /https?:\/\/[\S]+/,
                         :message => "请正确输入网址，以http开头"
                       }


  set_table_name 'weblink'

end

app/controllers/admin/friendlinks_controller.rb
# encoding: utf-8

class Admin::FriendlinksController < Admin::ApplicationController

	layout "admin"

  def index
    @friendlinks = Friendlink.all

    respond_to do |format|
      format.html
    end
  end

  def new
    @friendlink = Friendlink.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @friendlink = Friendlink.find(params[:id])
  end

   # POST /posts
  def create
    @friendlink = Friendlink.new(params[:friendlink])
    respond_to do |format|
      if @friendlink.save
        format.html { redirect_to admin_friendlinks_url, notice: '添加成功!' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @friendlink = Friendlink.find(params[:id])

    respond_to do |format|
      if @friendlink.update_attributes(params[:friendlink])
        format.html { redirect_to admin_friendlinks_url, notice: '下载修改成功!' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @friendlink = Friendlink.find(params[:id])
    @friendlink.destroy

    respond_to do |format|
      format.html { redirect_to admin_friendlinks_url }
    end
  end

end

app/views/admin/friendlinks/_form.html.erb
<% content_for(:nav)  do %>
  <li>
    <a href="<%= admin_friendlinks_path %>">友情连接</a><span class="divider">/</span>
  </li>
  <li>
  <li class="active"><%= @friendlink.web_name %></li> 
<% end %>


<%= form_for [:admin, @friendlink] do |f| %>

  <% if @friendlink.errors.any? %>
    <div id="error_explanation">
      
      <div class="alert alert-error">
        <button class="close" data-dismiss="alert">&times;</button>
        <strong>错误!</strong> 
        <span>发生了<%= pluralize(@friendlink.errors.count, "") %>个错误！</span>
        <ul>
        <% @friendlink.errors.messages.each do |msg| %>
          <li><%= msg.last.first %></li>
        <% end %>
        </ul>
      </div>

    </div>
  <% end %>

  <% errors = @friendlink.errors.messages %>

  <div class="field">
    <span>
      <%= f.label :名称 %>
      <input type="text" name="friendlink[web_name]" value="<%= @friendlink.web_name %>" />
    </span>
    <span style="color:#f60;"><%= "#{errors[:web_name].first}" if errors[:web_name] %></span>
  </div>  

  <div class="field">
    <%= f.label :网址 %>
    <%= f.text_field :url %>网址请于http开头!
    <span style="color:#f60;"><%= "#{errors[:url].first}" if errors[:url] %></span>
  </div>

  <div class="actions">
    <%= f.submit "确 定" %>
  </div>
<% end %>

app/views/admin/friendlinks/edit.html.erb
<h4>编辑友情连接</h4>

<%= render 'form' %>

<%= link_to '浏览', admin_friendlink_path(@friendlink) %> |
<%= link_to '返回', admin_friendlinks_path %>

app/views/admin/friendlinks/index.html.erb
<% content_for(:nav)  do %>
  <li>
    <a href="<%= admin_friendlinks_path %>">友情链接</a>
  </li> 
<% end %>

<div class="row-fluid">

  <div>
     <a href="<%= new_admin_friendlink_path %>" class="btn btn-primary"><i class="icon-plus icon-white"></i> 添加友情链接</a>
  </div>

  <!-- block -->
  <div class="block">
      <div class="navbar navbar-inner block-header">
          <div class="muted pull-left">友情链接</div>         
      </div>
      <div class="block-content collapse in">
          <table class="table table-striped">
              <thead>
                  <tr>
                      <th>网址名称</th>
                      <th width="450">网址</th>
                      <th width="190">操作</th>
                  </tr>
              </thead>
              <tbody>

                <% @friendlinks.each do |friendlink| %>
                  <tr>
                    <td><%= friendlink.web_name %></td>
                    <td><%= friendlink.url %></td>
                    <td>
                        <a href="<%= edit_admin_friendlink_path(friendlink) %>" class="btn btn-primary btn-mini"><i class="icon-pencil icon-white"></i> 编辑</a>
                        &nbsp;&nbsp;
                        <a href="<%= admin_friendlink_path(friendlink) %>" rel="nofollow" data-method="delete" data-confirm="确定要删除吗？" class="btn btn-danger btn-mini"><i class="icon-remove icon-white"></i> 删除</a>

                    </td>                   
                  </tr>
                <% end %>
              
              </tbody>
          </table>
      </div>
  </div>
  <!-- /block -->
</div>  

app/views/admin/friendlinks/new.html.erb
<h4>添加友情连接</h4>

<%= render 'form' %>

<%= link_to '返回', admin_friendlinks_path %>