config/routes.rb
Ckm::Application.routes.draw do
 

  get 'upload' => 'uploads#index'
  post 'upload' => 'uploads#upload'

  get "/bbs/" => redirect("/bbs/forum.php")
  # get '/bbs/:name', to: redirect('/bbs/%{name}')

  #get '/bbs/(:name)', to: redirect('http://www.chekuaimei.com/bbs/%{name}'), constraints: lambda { |request| ['www.ckm888.com', 'ckm888.com', '121.199.5.92'].include?(request.host) }

  mount UeditorRails::Engine => '/ueditor'

  get "service/category/:id/(page/:page)" => "service#category", :as => :category
  resources :service
  resources :downloads
  get "contact" => "contact#index"
  resources :shenqing
  resources :news do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :jiameng
  resources :zs

  get 'about/' => redirect("/about/1")
  get 'about/(:id)' => 'abouts#show'
  # get 'about/(:id)' => 'abouts#show', :constraints => {:id => /[1-4]/}

  resources :partners do
    get 'code/(:code)' =>  "partners#code", :on => :collection
  end

  namespace :admin do
    get 'showpartners/(:id)' => 'agents#get_partners'
    get 'regions/(:id)' => 'partners#get_regions'


    resources :qqs
    resources :friendlinks
    resources :shenqings
    resources :jiamengs
    resources :downloads
    resources :teams
    resources :shops
    resources :partners
    resources :users
    resources :sessions
    get 'sessions/logout' => 'sessions#destroy'

    get "" => 'home#index'
    # resources :admin

    # Directs /admin/products/* to Admin::ProductsController
    # (app/controllers/admin/products_controller.rb)
    resources :products
    resources :categories
    resources :indexsets
    resources :articles
    resources :zhaoshangs
    resources :abouts
    resources :agents
  end

  root :to => 'home#index'

end

app/models/jiameng.rb
# encoding: utf-8

class Jiameng < ActiveRecord::Base
  attr_accessible :title, :content, :ty_id, :state

  validates :title, :presence => { :message => "新闻标题不能为空" }

  set_table_name 'article'

  def state_name    
    re = nil
    if self.state == 1
      re = "启用"
    elsif self.state == 0
      re = "禁用"    
    end
    re 
  end    
    
  def state_name=(name)    
    # split = name.split(' ', 2)    
    # self.first_name = split.first    
    # self.last_name = split.last    
  end 
end

app/controllers/admin/jiamengs_controller.rb
# encoding: utf-8

class Admin::JiamengsController < Admin::ApplicationController


  layout "admin"

  def index
    @jiamengs = Jiameng.where(:ty_id => 5)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @jiameng = Jiameng.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @jiameng = Jiameng.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @jiameng = Jiameng.find(params[:id])
  end

  def create
    @jiameng = Jiameng.new(params[:jiameng])
    @jiameng.pulishdate = Time.now
    @jiameng.ty_id = 5

    respond_to do |format|
      if @jiameng.save
        format.html { redirect_to admin_jiameng_url(@jiameng), notice: '添加成功！' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @jiameng = Jiameng.find(params[:id])

    respond_to do |format|
      if @jiameng.update_attributes(params[:jiameng])
        format.html { redirect_to admin_jiamengs_url, notice: '修改成功!' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @jiameng = Jiameng.find(params[:id])
    @jiameng.destroy

    respond_to do |format|
      format.html { redirect_to admin_jiamengs_url }
    end
  end


end

app/controllers/jiameng_controller.rb
# encoding: utf-8

class JiamengController < ApplicationController

  def index
    @jiamengs = Jiameng.where(:ty_id => 5)
    @jiameng = @jiamengs.first
    
  end
 
  def show 
    @jiamengs = Jiameng.where(:ty_id => 5)
    @jiameng = Jiameng.find(params[:id])
  end

end

app/views/admin/jiamengs/_form.html.erb
<% content_for(:nav)  do %>
  <li>
    <a href="<%= admin_jiamengs_path %>">走进车快美</a><span class="divider">/</span>
  </li>
  <li>
  <li class="active"><%= @jiameng.title %></li> 
<% end %>

<%= form_for [:admin, @jiameng] do |f| %>

  <% if @jiameng.errors.any? %>
    <div id="error_explanation">
      
      <div class="alert alert-error">
        <button class="close" data-dismiss="alert">&times;</button>
        <strong>错误!</strong> 
        <span>发生了<%= pluralize(@jiameng.errors.count, "") %>个错误！</span>
        <ul>
        <% @jiameng.errors.messages.each do |msg| %>
          <li><%= msg.last.first %></li>
        <% end %>
        </ul>
      </div>

    </div>
  <% end %>

  <% errors = @jiameng.errors.messages %>

<div class="field">
    <span>
      <%= f.text_field :title %>
    </span>
    <span style="color:#f60;"><%= "#{errors[:title].first}" if errors[:title] %></span>
  </div>

  <div class="field">
    <%= f.label :状态 %><br />
    启用:<%= f.check_box :state, :checked => true %>
    <span style="color:#f60;"><%= "#{errors[:state].first}" if errors[:state] %></span>
  </div>

  <div class="field">
    <%= f.ueditor_text :content %>
    <span style="color:#f60;"><%= "#{errors[:content].first}" if errors[:content] %></span>
  </div>

  <div class="actions">
    <%= f.submit '确定' %>
  </div>
<% end %>

app/views/admin/jiamengs/edit.html.erb
<%= render 'form' %>

<%= link_to '预览', admin_jiameng_path(@jiameng) %> |
<%= link_to '返回', admin_jiamengs_path %>

app/views/admin/jiamengs/index.html.erb
<% content_for(:nav)  do %>
  <li>
    <a href="<%= admin_jiamengs_path %>">走进车快美</a>
  </li> 
<% end %>

<div class="row-fluid">

  <div>
     <a href="<%= new_admin_jiameng_path %>" class="btn btn-primary"><i class="icon-plus icon-white"></i> 添加</a>
  </div>

  <!-- block -->
  <div class="block">
      <div class="navbar navbar-inner block-header">
          <div class="muted pull-left">走进车快美</div>         
      </div>
      <div class="block-content collapse in">
          <table class="table table-striped">
              <thead>
                  <tr>
                      <th width="110">名称</th>
                      <th width="120">状态</th>
                      <th width="120">操作</th>
                  </tr>
              </thead>
              <tbody>

                <% @jiamengs.each do |jiameng| %>
                  <tr>
                    <td><%= jiameng.title %></td>
                    <td><%= jiameng.state_name %></td>
                    <td>
                        <a href="<%= admin_jiameng_path(jiameng) %>" class="btn btn-mini"><i class="icon-eye-open"></i> 浏览</a>
                        <a href="<%= edit_admin_jiameng_path(jiameng) %>" class="btn btn-primary btn-mini"><i class="icon-pencil icon-white"></i> 编辑</a>
                        <a href="<%= admin_jiameng_path(jiameng) %>" rel="nofollow" data-method="delete" data-confirm="确定要删除吗？" class="btn btn-danger btn-mini"><i class="icon-remove icon-white"></i> 删除</a>
                    </td>                   
                  </tr>
                <% end %>
              
              </tbody>
          </table>
      </div>
  </div>
  <!-- /block -->
</div>  

app/views/admin/jiamengs/new.html.erb
<h4>添加</h4>

<%= render 'form' %>

<%= link_to '返回', admin_jiamengs_path %>

app/views/admin/jiamengs/show.html.erb
<% content_for(:nav)  do %>
  <li>
    <a href="<%= admin_jiamengs_path %>">走进车快美</a> <span class="divider">/</span> 
  </li>
  <li class="active"><%= @jiameng.title %></li>
<% end %>

<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>操作提示</h4>
    <%= notice %>
  </div>
<% end %>


<h4><%= @jiameng.title %></h4>


<p>
  <b>状态:</b>
  <%= @jiameng.state_name %>
</p>

<p>
  <%= raw @jiameng.content %>
</p>


<%= link_to '编辑', edit_admin_jiameng_path(@jiameng) %> |
<%= link_to '返回', admin_jiamengs_path %>