config/routes.rb
Ckm::Application.routes.draw do
 

  get 'upload' => 'uploads#index'
  post 'upload' => 'uploads#upload'

  get "/bbs/" => redirect("/bbs/forum.php")
  # get '/bbs/:name', to: redirect('/bbs/%{name}')

  #get '/bbs/(:name)', to: redirect('http://www.chekuaimei.com/bbs/%{name}'), constraints: lambda { |request| ['www.ckm888.com', 'ckm888.com', '121.199.5.92'].include?(request.host) }

  mount UeditorRails::Engine => '/ueditor'

  get "service/category/:id/(page/:page)" => "service#category", :as => :category
  resources :service
  resources :downloads
  get "contact" => "contact#index"
  resources :shenqing
  resources :news do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :jiameng
  resources :zs

  get 'about/' => redirect("/about/1")
  get 'about/(:id)' => 'abouts#show'
  # get 'about/(:id)' => 'abouts#show', :constraints => {:id => /[1-4]/}

  resources :partners do
    get 'code/(:code)' =>  "partners#code", :on => :collection
  end

  namespace :admin do
    get 'showpartners/(:id)' => 'agents#get_partners'
    get 'regions/(:id)' => 'partners#get_regions'


    resources :qqs
    resources :friendlinks
    resources :shenqings
    resources :jiamengs
    resources :downloads
    resources :teams
    resources :shops
    resources :partners
    resources :users
    resources :sessions
    get 'sessions/logout' => 'sessions#destroy'

    get "" => 'home#index'
    # resources :admin

    # Directs /admin/products/* to Admin::ProductsController
    # (app/controllers/admin/products_controller.rb)
    resources :products
    resources :categories
    resources :indexsets
    resources :articles
    resources :zhaoshangs
    resources :abouts
    resources :agents
  end

  root :to => 'home#index'

end

app/models/qq.rb
# encoding: utf-8

class Qq < ActiveRecord::Base
  attr_accessible :number, :bz

  validates :number, :presence => { message: "QQ号码不能为空!"}
  validates :bz, :presence => { message: "QQ备注不能为空!"}

end

app/controllers/admin/qqs_controller.rb
# encoding: utf-8

class Admin::QqsController < ApplicationController
  layout "admin"

	 def index
    @qqs = Qq.all

    respond_to do |format|
      format.html 
    end
  end

  def show
    @qq = Qq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @qq = Qq.new
    # binding.pry
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @qq = Qq.find(params[:id])
  end

  def create
    @qq = Qq.new(params[:qq])
    respond_to do |format|
      if @qq.save
        format.html { redirect_to admin_qqs_url, notice: '添加成功!' }
      else
        # binding.pry
        format.html { render action: "new" }
      end
    end
  end

  def update
    @qq = Qq.find(params[:id])
   
    respond_to do |format|
      if @qq.update_attributes(params[:qq])
        format.html { redirect_to admin_qqs_url, notice: '修改成功!' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @qq = Qq.find(params[:id])
    @qq.destroy

    respond_to do |format|
      format.html { redirect_to admin_qqs_url }
    end
  end

end

app/helpers/admin/qqs_helper.rb
module Admin::QqsHelper
end

app/views/admin/qqs/_form.html.erb
<% content_for(:nav)  do %>
  <li>
    <a href="<%= admin_qqs_path %>">QQ在线</a><span class="divider">/</span>
  </li>
  <li>
  <li class="active"><%= @qq.bz %></li> 
<% end %>


<%= form_for [:admin, @qq] do |f| %>

  <% if @qq.errors.any? %>
    <div id="error_explanation">
      
      <div class="alert alert-error">
        <button class="close" data-dismiss="alert">&times;</button>
        <strong>错误!</strong> 
        <span>发生了<%= pluralize(@qq.errors.count, "") %>个错误！</span>
        <ul>
        <% @qq.errors.messages.each do |msg| %>
          <li><%= msg.last.first %></li>
        <% end %>
        </ul>
      </div>

    </div>
  <% end %>

  <% errors = @qq.errors.messages %>

  <div class="field">
    <span>
      <%= f.label :名称 %>
      <input type="text" name="qq[bz]" value="<%= @qq.bz %>" />
    </span>
    <span style="color:#f60;"><%= "#{errors[:bz].first}" if errors[:bz] %></span>
  </div>  

  <div class="field">
    <%= f.label :号码 %>
    <%= f.text_field :number %>
    <span style="color:#f60;"><%= "#{errors[:number].first}" if errors[:number] %></span>
  </div>

  <div class="actions">
    <%= f.submit "确 定" %>
  </div>
<% end %>

app/views/admin/qqs/edit.html.erb
<h4>编辑qq</h4>

<%= render 'form' %>

<%= link_to '浏览', admin_qq_path(@qq) %> |
<%= link_to '返回', admin_qqs_path %>

app/views/admin/qqs/index.html.erb
<% content_for(:nav)  do %>
  <li>
    <a href="<%= admin_qqs_path %>">在线QQ</a>
  </li> 
<% end %>

<div class="row-fluid">

  <div>
     <a href="<%= new_admin_qq_path %>" class="btn btn-primary"><i class="icon-plus icon-white"></i> 添加QQ</a>
  </div>

  <!-- block -->
  <div class="block">
      <div class="navbar navbar-inner block-header">
          <div class="muted pull-left">在线QQ</div>         
      </div>
      <div class="block-content collapse in">
          <table class="table table-striped">
              <thead>
                  <tr>
                      <th>名称</th>
                      <th width="450">号码</th>
                      <th width="190">操作</th>
                  </tr>
              </thead>
              <tbody>

                <% @qqs.each do |qq| %>
                  <tr>
                    <td><%= qq.bz %></td>
                    <td><%= qq.number %></td>
                    <td>
                        <a href="<%= edit_admin_qq_path(qq) %>" class="btn btn-primary btn-mini"><i class="icon-pencil icon-white"></i> 编辑</a>
                        &nbsp;&nbsp;
                        <a href="<%= admin_qq_path(qq) %>" rel="nofollow" data-method="delete" data-confirm="确定要删除吗？" class="btn btn-danger btn-mini"><i class="icon-remove icon-white"></i> 删除</a>

                    </td>                   
                  </tr>
                <% end %>
              
              </tbody>
          </table>
      </div>
  </div>
  <!-- /block -->
</div>  

app/views/admin/qqs/new.html.erb
<h4>添加qq</h4>

<%= render 'form' %>

<%= link_to '返回', admin_qqs_path %>