config/routes.rb
Ckm::Application.routes.draw do
 

  get 'upload' => 'uploads#index'
  post 'upload' => 'uploads#upload'

  get "/bbs/" => redirect("/bbs/forum.php")
  # get '/bbs/:name', to: redirect('/bbs/%{name}')

  #get '/bbs/(:name)', to: redirect('http://www.chekuaimei.com/bbs/%{name}'), constraints: lambda { |request| ['www.ckm888.com', 'ckm888.com', '121.199.5.92'].include?(request.host) }

  mount UeditorRails::Engine => '/ueditor'

  get "service/category/:id/(page/:page)" => "service#category", :as => :category
  resources :service
  resources :downloads
  get "contact" => "contact#index"
  resources :shenqing
  resources :news do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :jiameng
  resources :zs

  get 'about/' => redirect("/about/1")
  get 'about/(:id)' => 'abouts#show'
  # get 'about/(:id)' => 'abouts#show', :constraints => {:id => /[1-4]/}

  resources :partners do
    get 'code/(:code)' =>  "partners#code", :on => :collection
  end

  namespace :admin do
    get 'showpartners/(:id)' => 'agents#get_partners'
    get 'regions/(:id)' => 'partners#get_regions'


    resources :qqs
    resources :friendlinks
    resources :shenqings
    resources :jiamengs
    resources :downloads
    resources :teams
    resources :shops
    resources :partners
    resources :users
    resources :sessions
    get 'sessions/logout' => 'sessions#destroy'

    get "" => 'home#index'
    # resources :admin

    # Directs /admin/products/* to Admin::ProductsController
    # (app/controllers/admin/products_controller.rb)
    resources :products
    resources :categories
    resources :indexsets
    resources :articles
    resources :zhaoshangs
    resources :abouts
    resources :agents
  end

  root :to => 'home#index'

end

app/models/indexset.rb
# encoding: utf-8

class Indexset < ActiveRecord::Base
  attr_accessible :module, :title, :picture, :url

  set_table_name "indexset"

  validates :module, :presence => { :message => "不能为空" }

end

app/controllers/admin/indexsets_controller.rb
# encoding: utf-8

class Admin::IndexsetsController < Admin::ApplicationController
  layout "admin"

  def index
    @indexsets = Indexset.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @indexset = Indexset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @indexset = Indexset.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @indexset = Indexset.find(params[:id])
  end

  def create
    @indexset = Indexset.new(params[:indexset])
    @indexset.date = Time.now
    @indexset.picture = uploadFile(params[:indexset]["picture"]) if params[:indexset]["picture"]   
    # binding.pry

    respond_to do |format|
      if @indexset.save
        format.html { redirect_to admin_indexset_url(@indexset), notice: '添加成功！' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @indexset = Indexset.find(params[:id])
    tmp =  params[:indexset]
    tmp[:picture] = uploadFile(params[:indexset]["picture"])  if params[:indexset]["picture"]

    respond_to do |format|
      if @indexset.update_attributes(tmp)
        format.html { redirect_to admin_indexset_url(@indexset), notice: '更新成功！' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @indexset = Indexset.find(params[:id])
    @indexset.destroy

    respond_to do |format|
      format.html { redirect_to admin_indexsets_url }
    end
  end


end

app/views/admin/indexsets/_form.html.erb
<%= form_for [:admin, @indexset] do |f| %>

  <% if @indexset.errors.any? %>
    <div id="error_explanation">
      
      <div class="alert alert-error">
        <button class="close" data-dismiss="alert">&times;</button>
        <strong>错误!</strong> 
        <span>发生了<%= pluralize(@indexset.errors.count, "") %>个错误！</span>
        <ul>
        <% @indexset.errors.messages.each do |msg| %>
          <li><%= msg.last.first %></li>
        <% end %>
        </ul>
      </div>

    </div>
  <% end %>

  <% errors = @indexset.errors.messages %>

  <br />
  <div class="field">
    <%= f.label :模块名称 %>
    <span><input type="text" name="indexset[module]" value="<%= @indexset.module %>" /></span>
    <span style="color:#f60;"><%= errors[:module].first if errors[:module] %></span>
  </div>

  <br />
  <div class="field">
    <%= f.label :标题 %>
    <%= f.text_field :title %>
    <span style="color:#f60;"><%= errors[:title].first if errors[:title] %></span>
  </div>

  <br />
  <div class="field">
    <%= f.label :图片 %>
    <%= f.file_field :picture %>
    <span style="color:#f60;"><%= "#{errors[:picture].first}" if errors[:picture] %></span>
  </div>

  <br />
  <div class="field">
    <%= f.label :链接地址 %>
    <%= f.text_field :url %>
    <span style="color:#f60;"><%= "#{errors[:url].first}" if errors[:url] %></span>
  </div>

  <div class="actions">
    <%= f.submit "确 定" %>
  </div>
<% end %>

app/views/admin/indexsets/index.html.erb
<% content_for(:nav)  do %>
  <li>
    <a href="<%= admin_indexsets_path %>">首页模块设置</a>
  </li> 
<% end %>

<div class="row-fluid">

<!-- <div>
     <a href="<%= new_admin_indexset_path %>" class="btn btn-primary"><i class="icon-plus icon-white"></i> 添加模块设计</a>
</div> -->

  <!-- block -->
  <div class="block">
      <div class="navbar navbar-inner block-header">
          <div class="muted pull-left">首页模块设置</div>         
      </div>
      <div class="block-content collapse in">
          <table class="table table-striped">
              <thead>
                  <tr>
                      <td width="55">图片</td>
                      <td width="85">模块名称</td>
                      <th>备注说明</th>
                      <td width="110">
                        <div  style="overflow: hidden;width:110px;">链接地址</div></td>
                      <th width="130">操作</th>
                  </tr>
              </thead>
              <tbody>

                <% @indexsets.each do |indexset| %>
                  <tr>
                    <td><div style="width:50px;overflow:hidden;">
                      <%= image_tag(indexset.picture, {:width => "50", :height => "50"}) if indexset.picture %></div>
                    </td>
                    <td><%= indexset.module %></td>
                    <td><%= indexset.title %></td>
                    <td><div  style="overflow: hidden;width:100px;"><%= indexset.url %></div></td>
                    <td>
                      <a href="<%= admin_indexset_path(indexset) %>" class="btn btn-mini"><i class="icon-eye-open"></i> 浏览</a>
                        &nbsp;
                        <a href="<%= edit_admin_indexset_path(indexset) %>" class="btn btn-primary btn-mini"><i class="icon-pencil icon-white"></i> 编辑</a>
                        <!-- &nbsp;
                        <a href="<%= admin_indexset_path(indexset) %>" rel="nofollow" data-method="delete" data-confirm="确定要删除吗？" class="btn btn-danger btn-mini"><i class="icon-remove icon-white"></i> 删除</a> -->

                    </td>                   
                  </tr>
                <% end %>
              
              </tbody>
          </table>
      </div>
  </div>
  <!-- /block -->
</div>  

app/views/admin/indexsets/new.html.erb
<h1>创建首页设置</h1>

<%= render 'form' %>

<%= link_to '返回', admin_indexsets_path %>

app/views/admin/indexsets/show.html.erb
<% if  notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>操作提示</h4>
    <%= notice %>
  </div>
<% end %>

<p>
  <b>模块名称:</b>
  <%= @indexset.module %>
</p>

<p>
  <b>标题:</b>
  <%= @indexset.title %>
</p>

<p>
  <b>图片:</b>
  <%= image_tag(@indexset.picture) %>
</p>

<p>
  <b>链接地址:</b>
  <%= raw @indexset.url %>
</p>


<%= link_to '编辑', edit_admin_indexset_path(@indexset) %> |
<%= link_to '返回', admin_indexsets_path %>